### ISSUE TITLE
팀원 2분 구합니다

### ISSUE THREAD

**Issue by mustardlove** [swsnu/swppfall2019#1]
안녕하세요~
이번 소개원실 수업을 듣는 최한결(컴공 15), 황한메(경제 14)이라고 합니다:)
팀원 두 분 구합니다!!!
드랍 안하시고 끝까지 같이 열심히 하실 분들 저희와 함께 해요!
관심 있으신 분들 카톡 아이디 "ghkdgksap"("황한메")로 연락주세요!

감사합니다

**Comment by ybzzang** [comment]
카톡 친구 검색이 안되네요ㅠ.ㅠ

**Comment by Peace-Song** [comment]
저두요 ㅠㅠ

**Comment by mustardlove** [comment]
죄송합니다 방금 검색 기능 켰어요!! 두분 연락주시기 바랍니다 ㅠㅠ

**Comment by mustardlove** [comment]
팀원 구성이 완료되었습니다
