### ISSUE TITLE
[HW3] 사소한 스펙상 질문이 있습니다.

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swppfall2019#131]
안녕하세요, HW3 스펙에 대해 사소한 질문이 있습니다.

1. CSRF 토큰을 사용해야 하나요?
2. 기술되어있는 URL 마지막에 `/`가 없지만, 마지막에 항상 `/`가 붙어있다고 생각하면 될까요?

감사합니다.

**Comment by ktaebum** [comment]
1. 네 사용하셔야 합니다.
2. 네 항상 붙어 있다고 생각해주세요
