### ISSUE TITLE
[HW3] 입출력에 관한 질문이 있습니다. | I have a question on spec IO

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swppfall2019#132]
안녕하세요, 마지막 질문이 있습니다.

입출력에 대해서 스펙에서는 다음과 같이 명시하고 있습니다:
```
User : {username: string, password: string}
Article : {title: string, content: string}
Comment : {content: string}
```
입출력시에 항상 이 스펙을 따라야 하나요?
특히, `GET api/article`, `GET api/article/:article_id`, `GET api/article/:article_id/comment`, `GET api/comment/:comment_id` 에서는 `author` 또는 `article` 에 대해 `id` 를 출력하라고 명시되어있는데, 이런 경우도 `author_id`, `article_id` 가 아닌 `author`, `article` 을 출력 dictionary 의 key로 해야 하나요? 아니면 상관 없을까요?

---
README file specifies IO as follows:
```
User : {username: string, password: string}
Article : {title: string, content: string}
Comment : {content: string}
```
and specifies REST APIs as follows:

in `GET api/article`, `GET api/article/:article_id`, `GET api/article/:article_id/comment` and `GET api/comment/:comment_id`: `the value of the article and the author must be the id of the article and the author but not the title and her username.`

What should be the key of `article id` in dictionary as a response?

**Comment by ktaebum** [comment]
네 `POST`, `PUT`에 대해서 저 스펙을 따라주셔야 합니다

GET에 대한 json response를 받아올 때 키 값은 `author`, `article`로 해주세요 (not `*_id`)
