### ISSUE TITLE
hw3 제출 관련해서 문의드립니다

### ISSUE THREAD

**Issue by jangsus1** [swsnu/swppfall2019#185]
제가 add를 하지 않고 commit과 push만 하다가 제출 기한 5분 후에 push가 정상적으로 이루어지지 못하였다는 것을 알게 되어 commit과 push를 바로 하였는데 혹시 이 부분에 대하여 delay에 의한 감점처리는 불가능한지 여쭙고 싶습니다.

**Comment by hy00nc** [comment]
정상 제출 처리하겠습니다.
