### ISSUE TITLE
[HW2] hw2 관련 질문있습니다. / I have a question on hw2.

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swppfall2019#51]
1. 로그인 된 상태에서 페이지를 새로고침하는 경우도 고려해야 하나요?
2. 만약 그렇다면, 쿠키나 `localStorage` 등을 사용해도 될까요?
3. 로그인 후 화면에 표시된 링크만을 따라가는 것이 아닌 주소창에 `http:///localhost:8000/articles/:id/edit` 등을 입력하는 경우도 고려해야 하나요?

---

1. Should I consider refreshing page while logged in?
2. If so, can I use `cookie` or `localStorage`?
3. Should I consider user not following specified links and entering specific address directly, like `http://localhost:8000/articles/:id/edit` after login?

**Comment by ktaebum** [comment]
1. We will not consider refreshing page while grading. It's up to you
2. Anyway you can use `cookie` or `localStorage`
3. No. We will not consider entering the specific address directly. We will consider the navigation flow of storyboard image.

---

1. 채점을 하면서 중간에 새로고침을 하면서 채점을 하진 않으니 자유롭게 해주시면 됩니다.
2. 그와 별개로 사용하셔도 됩니다.
3. 해당 링크로 바로 가는 것은 고려하지 않구요, 스토리 보드 그림에 나와있는 flow만 고려를 하시면 됩니다
